CC = gcc
CFLAGS = -std=c99 -Wall -g

explore-int: explore-int.c
	$(CC) $(CFLAGS) -o explore-int explore-int.c

fact-pointer: fact-pointer.c
	$(CC) $(CFLAGS) -o fact-pointer fact-pointer.c

pointers-torture-test: pointers-torture-test.c
	$(CC) $(CFLAGS) -o pointers-torture-test pointers-torture-test.c

swap: swap.c
	$(CC) $(CFLAGS) -o swap swap.c

stack-return: stack-return.c
	$(CC) $(CFLAGS) -o stack-return stack-return.c

point_prog: point.h point.c point_prog.c
	$(CC) $(CFLAGS) -o point_prog point.c point_prog.c
