CDCC = gcc
CFLAGS = -std=c99 -Wall -g

buggy-source : buggy-source.c
	$(CC) $(CFLAGS) -o buggy-source buggy-source.c

buggy-source-more : buggy-source-more.c
	$(CC) $(CFLAGS) -o buggy-source-more buggy-source-more.c